### PR TITLE
Fix bugs regarding Grade

### LINKED ISSUE #174: Parameters - Grade allows -1
Currently, you can edit Grade as -1.

We use -1 as an indicator that Grade is NA, but this is not revealed to the user.

Perhaps we can allow NA and reject -1, as TAs may make a mistake while editing Grade and may want to unmark it.

### LINKED ISSUE #204: Edit Command - Grade -1 can still be added
When I typed in `edit /id A0000000A /grade -1`, the successful edit message was still shown instead of an error message of invalid grade (0-100). Only for grade `-1` does this behavior occur; other invalid ones have been mentioned in #192.

Image

### PR DESCRIPTION
**Pull request by Billy026**
Fixes #174 
Fixes #204

### CODE REVIEW

File: src/test/java/seedu/address/testutil/PersonUtil.java [hunk 1]
```diff
@@ -55,8 +55,10 @@ public static String getEditPersonDescriptorDetails(EditPersonDescriptor descrip
                 .append(attendance.status).append(" "));
         descriptor.getParticipation().ifPresent(participation -> sb.append(PREFIX_PARTICIPATION)
                 .append(" ").append(participation.status).append(" "));
-        descriptor.getGrade().ifPresent(grade -> sb.append(PREFIX_GRADE).append(" ").append(grade.grade)
-                .append(" "));
+        descriptor.getGrade().ifPresent(grade -> {
+                String gradeValue = (grade.grade == -1) ? "NA" : String.valueOf(grade.grade);
+                sb.append(String.format("%s %s ", PREFIX_GRADE, gradeValue));
+        });
```
Comment (minhkiwi14) [inline src/test/java/seedu/address/testutil/PersonUtil.java:61]: Checkstyle is complaining :( I will fix it now.

**Review by minhkiwi14 — COMMENTED** [review]
LGTM despite checkstyle things

**Comment by minhkiwi14** [comment]
Will fix checkstyle in another PR
