### PR TITLE
Fix format for delete command

### LINKED ISSUE #111: Fix delete command usage format
Change the format for using delete from 
> delete \<id\>

to
> delete /id \<id\>

### PR DESCRIPTION
**Pull request by VikramGoyal23**
Fixes #111

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -17,13 +18,18 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
...
+                    || !argMultimap.getPreamble().isEmpty()) {
+                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE));
+            }
+            Id id = ParserUtil.parseId(argMultimap.getValue(PREFIX_ID).get());
             return new DeleteCommand(id);
-        } catch (ParseException pe) {
-            throw new ParseException(
-                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE), pe);
-        }
+//        } catch (ParseException pe) {
```
Comment (0xF41) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java:29]: lgtm can omit this part
