### PR TITLE
Fix bugs regarding name

### LINKED ISSUE #167: Parameters - Allow Special Symbols in Name
Names should allow all symbols, and not be alphanumeric only.

### PR DESCRIPTION
**Pull request by Billy026**
Fixes #167 and #168

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -38,6 +39,27 @@ public static boolean isValidName(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    /**
+     * Returns the name without extra spaces.
+     * Extra spaces are defined as more than one space between words.
+     */
+    public static String trimExtraSpaces(String name) {
```
Comment (0xF41) [inline src/main/java/seedu/address/model/person/Name.java:46]: LGTM

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 2]
```diff
@@ -70,14 +70,23 @@ public class CommandTestUtil {
...
 
-    public static final String INVALID_ID_DESC = " " + PREFIX_ID + "";
-    public static final String INVALID_NAME_DESC = " " + PREFIX_NAME + " James&"; // '&' not allowed in names
-    public static final String INVALID_PHONE_DESC = " " + PREFIX_PHONE + " 911a"; // 'a' not allowed in phones
-    public static final String INVALID_EMAIL_DESC = " " + PREFIX_EMAIL + " bob!yahoo"; // missing '@' symbol
-    public static final String INVALID_COURSE_DESC = " " + PREFIX_COURSE + "";
-    public static final String INVALID_ATTENDANCE_DESC = " " + PREFIX_ATTENDANCE + "";
-    public static final String INVALID_PARTICIPATION_DESC = " " + PREFIX_PARTICIPATION + "";
-    public static final String INVALID_GRADE_DESC = " " + PREFIX_GRADE + "";
+    public static final String INVALID_ID = "A1234567"; // No ending letter
```
Comment (0xF41) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:73]: valid stuff

**Review by 0xF41 — CHANGES_REQUESTED** [review]
Did you re test junit tests that deal with `Name`? Nevermind i am high
